### ISSUE TITLE
Installation tutorial

### ISSUE THREAD

**Issue by Enngage** [juraju-kentico/react-tutorial-js#1]
Since the scripts in package.json expects globally installed packages, the installation in here is not valid until user specifically installs those packages as global. Can you add information readme as to what packages user needs to install?

**Comment by juraju-kentico** [comment]
You are right that `npm install` is missing from the Readme, I will add it there. 

But I don't think `package.json` expects globally installed packages, npm scripts should automatically add node modules to their PATH:
https://firstdoit.com/no-need-for-globals-using-npm-dependencies-in-npm-scripts-3dfb478908
https://michael-kuehnel.de/tooling/2018/03/22/helpers-and-tips-for-npm-run-scripts.html

I have uninstalled my global create-react-app and it still works, so I think running `npm install` and `npm start` should be enough the get the app running.

**Comment by Enngage** [comment]
If that works, great :) I know that I've had some issues with these and had to add paths to my scripts manually, but thats maybe because the executable of some packages are in different folders. Closing then.
