### ISSUE TITLE
File naming convention

### ISSUE THREAD

**Issue by Enngage** [juraju-kentico/react-tutorial-js#2]
Is there any reason why some files are lowercase and some PascalCase? For example 'registerServiceWorker.js' and 'DeliveryClientConfig.js' ? Can we unify this?

**Comment by juraju-kentico** [comment]
Good point. I have deleted `registerServiceWorker` and renamed `DeliveryClientConfig` to `deliveryClientConfig`. Every React project basically has its own conventions, but here it should be: all lower-camelcase, except names of Components, which are capitalized.
