### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by Enngage** [juraju-kentico/react-tutorial-js#3]
I get that this is a tutorial, but do we really want to have all files in same folder? I'm not familiar with react, but I suspect there is at least some 'recommended' structure that we could (should) follow.

**Comment by juraju-kentico** [comment]
I have deleted some of the redundant files, so now its just 8 files in the `src` folder. 

We could create some folders a move files around, but then you would have to ask readers to do that during the tutorial. That's an extra step with little educational value, they might skip it, which would break copy-pasting examples (they would have to fix their imports every time). Not sure it is worth it, but it could be. Will discuss with TWs during review/testing. Thanks!
