### ISSUE TITLE
Scope for 'unsubscribeSubject'

### ISSUE THREAD

**Issue by Enngage** [juraju-kentico/react-tutorial-js#4]
I'm not sure if having `unsubscribeSubject` outside the react component class is the proper way of initializing subject. I would think that in order for this property to be properly managed (garbage collected, initialized at the right time, tore down..) it should reside inside the react class. 

Can you try moving it there and see how that works?  E.g. https://github.com/juraju-kentico/react-tutorial-js/blob/master/src/ArticleListing.js#L7

**Comment by juraju-kentico** [comment]
Hmm, I agree it doesn't seem right, but initializing the subject inside the component (whether as a static property or inside the constructor) results in `undefined` errors. Any ideas how to make it work better?

**Comment by Enngage** [comment]
Since this is plain js, I think you should be able to create the subject
property in the constructor :-)

**Comment by jancerman** [comment]
Closing because this won't be resolved anymore.
