### ISSUE TITLE
refactor to use hooks

### ISSUE THREAD

**Issue by kstulgys** [juraju-kentico/react-tutorial-js#6]
**Is your feature request related to a problem? Please describe.**
Since all new React projects go with hooks now I would like to see the Kentico tutorial updated.

**Describe the solution you'd like**
I would like to refactor the current components to functional components and use hooks. useEffect - fetching articles, useState - storing articles.

**Additional context**
I have been using React and Kentico for a while now and looking for an opportunity to do my first OSS contribution.

**Comment by jancerman** [comment]
Hi @kstulgys, thanks for the interest! You can go ahead and refactor the code for the react tutorial. After you're done, I'll create a task for the docs team to update the [text around the code in the tutorial](https://docs.kontent.ai/tutorials/develop-apps/get-started/running-a-sample-application?tech=react).

**Comment by kstulgys** [comment]
Thanks, just opened a PR

**Comment by jancerman** [comment]
Resolved in https://github.com/Kentico/kontent-tutorial-react-js/pull/7. Closing.
